#!/usr/bin/env bash
# Configure UFW to forward port 8080/TCP to port 80/TCP

sudo sed -i 's/DEFAULT_FORWARD_POLICY="DROP"/DEFAULT_FORWARD_POLICY="ACCEPT"/' /etc/default/ufw

sudo sed -i '1i # NAT table configuration\n*nat\n:PREROUTING ACCEPT [0:0]\n-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\nCOMMIT\n' /etc/ufw/before.rules

sudo ufw allow 8080/tcp
sudo ufw reload
