#!/usr/bin/env bash
# Configures Nginx to return a custom HTTP header X-Served-By with the server hostname

apt-get update -y
apt-get install -y nginx

# Add custom HTTP header X-Served-By containing server hostname
sed -i "/server_name _;/a \    add_header X-Served-By \"\$HOSTNAME\";" /etc/nginx/sites-available/default

# Ensure Nginx service is running and reloaded
service nginx restart
