#!/usr/bin/env bash
# Configures Nginx to perform a 301 redirection for /redirect_me

apt-get update -y
apt-get install -y nginx

# Add 301 redirection inside server block using sed
sed -i '/server_name _;/a \    location /redirect_me {\n        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n    }' /etc/nginx/sites-available/default

# Set root content
echo "Holberton School" > /var/www/html/index.nginx-debian.html

service nginx restart
