#!/usr/bin/env bash
# Configures Nginx with a custom 404 page

apt-get update -y
apt-get install -y nginx

# Set default page content
echo "Holberton School" > /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html

# Set custom 404 page content
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html

# Configure custom 404 page in Nginx default configuration
sed -i '/server_name _;/a \    error_page 404 /custom_404.html;\n    location = /custom_404.html {\n        root /var/www/html;\n        internal;\n    }' /etc/nginx/sites-available/default

# Restart Nginx service
service nginx restart
