#!/usr/bin/env bash
# Configures Nginx server with a custom 404 page and 301 redirection

apt-get update -y
apt-get install -y nginx

# Set index pages and custom 404 page content
echo "Holberton School" > /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Overwrite default Nginx server configuration cleanly
cat << 'EOF' > /etc/nginx/sites-available/default
server {
    listen 80 default_server;
    listen [::]:80 default_server;

    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;

    server_name _;

    error_page 404 /404.html;
    location = /404.html {
        root /var/www/html;
        internal;
    }

    location / {
        try_files $uri $uri/ =404;
    }

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF

# Restart Nginx
service nginx restart
